[package]
name = "stm32f446_updt_fw"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stm32f446_updt_fw"
bench = false
doctest = false
test = false

[dependencies]
cortex-m = "0.7.1"
cortex-m-rt = "0.7.1"
rustBoot-hal ={path = "../../../hal",default-features = false,features = ["stm32f446"]}
panic-probe = { version = "0.3.0" }
rustBoot-update = {path = "../../../update", features = ["stm32f446"]}

# board-specific features
[dependencies.stm32f4xx-hal]
version = "0.13.1"
features = ["rt", "stm32f446"]
